name: Android CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Clean project
      run: ./gradlew clean

    - name: Run Unit Tests
      run: ./gradlew test --stacktrace

    - name: Build Debug APK
      run: ./gradlew assembleDebug --stacktrace

    # If tests pass, proceed with release build
    - name: Decode Keystore
      run: |
        echo "${{ secrets.KEYSTORE_FILE }}" | base64 -d > app/release-key.jks
      shell: bash

    - name: Create local.properties
      run: |
        echo "KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}" >> local.properties
        echo "KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> local.properties
        echo "KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" >> local.properties

    - name: Build Release APK
      run: ./gradlew assembleRelease --stacktrace
      env:
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

    - name: Upload Test Reports
      if: always() # Upload reports regardless of test outcome
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: app/build/reports/tests/

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: app/build/outputs/apk/release/app-release.apk