name: Android CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Decode Keystore
      run: |
        echo "${{ secrets.KEYSTORE_FILE }}" | base64 -d > release-key.jks
      shell: bash

    - name: Verify keystore file
      run: |
        ls -l release-key.jks
        file release-key.jks

    - name: Build Release APK
      run: ./gradlew assembleRelease --stacktrace
      env:
        SIGNING_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        SIGNING_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        SIGNING_STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Sign and Align APK
      run: |
        # Sign APK
        jarsigner -verbose \
          -keystore release-key.jks \
          -storepass ${{ secrets.KEYSTORE_PASSWORD }} \
          -keypass ${{ secrets.KEY_PASSWORD }} \
          app/build/outputs/apk/release/app-release-unsigned.apk \
          ${{ secrets.KEY_ALIAS }}

        # Verify signing
        jarsigner -verify \
          app/build/outputs/apk/release/app-release-unsigned.apk

        # Align APK
        ${ANDROID_HOME}/build-tools/34.0.0/zipalign -v 4 \
          app/build/outputs/apk/release/app-release-unsigned.apk \
          app-release.apk

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: app-release.apk