name: Android CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Clean project
      run: ./gradlew clean

    - name: Run Unit Tests
      run: ./gradlew test --stacktrace

    - name: Build Debug APK
      run: ./gradlew assembleDebug --stacktrace

    # Keystore handling using your exact secret names
    - name: Setup Keystore
      run: |
        echo "${{ secrets.KEYSTORE_FILE }}" > keystore.b64
        base64 -d keystore.b64 > app/release-key.jks
        rm keystore.b64
        # Verify keystore exists and alias is correct
        keytool -list -v \
          -keystore app/release-key.jks \
          -storepass "${{ secrets.KEYSTORE_PASSWORD }}" \
          -alias "${{ secrets.KEY_ALIAS }}" || exit 1
      shell: bash

    - name: Build Release APK
      run: |
        ./gradlew assembleRelease \
          -Pandroid.injected.signing.store.file=app/release-key.jks \
          -Pandroid.injected.signing.store.password=${{ secrets.KEYSTORE_PASSWORD }} \
          -Pandroid.injected.signing.key.alias=${{ secrets.KEY_ALIAS }} \
          -Pandroid.injected.signing.key.password=${{ secrets.KEY_PASSWORD }} \
          --stacktrace

    - name: Upload Test Reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: app/build/reports/tests/

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: app/build/outputs/apk/release/app-release.apk