name: Android CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Decode Keystore
      env:
        ENCODED_STRING: ${{ secrets.KEYSTORE_FILE }}
      run: |
        echo $ENCODED_STRING | base64 -d > app/release.keystore

    - name: Build Release APK
      run: ./gradlew assembleRelease
      env:
        SIGNING_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        SIGNING_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        SIGNING_STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}

    - name: Sign APK
      run: |
        jarsigner -verbose \
          -keystore app/release.keystore \
          -storepass ${{ secrets.KEYSTORE_PASSWORD }} \
          -keypass ${{ secrets.KEY_PASSWORD }} \
          app/build/outputs/apk/release/app-release-unsigned.apk \
          ${{ secrets.KEY_ALIAS }}

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Align APK
      run: |
        ${ANDROID_HOME}/build-tools/34.0.0/zipalign -v 4 \
          app/build/outputs/apk/release/app-release-unsigned.apk \
          app-release.apk

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: app-release.apk

    - name: Upload to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1.7.0
      with:
        appId: ${{secrets.FIREBASE_APP_ID}}
        serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
        groups: testers
        file: app-release.apk